package xyz.bluspring.unitytranslate.api.v2.client

import xyz.bluspring.unitytranslate.api.v2.UnityTranslateApi

enum class InputValue {
    KEY_0,
    KEY_1,
    KEY_2,
    KEY_3,
    KEY_4,
    KEY_5,
    KEY_6,
    KEY_7,
    KEY_8,
    KEY_9,
    KEY_A,
    KEY_B,
    KEY_C,
    KEY_D,
    KEY_E,
    KEY_F,
    KEY_G,
    KEY_H,
    KEY_I,
    KEY_J,
    KEY_K,
    KEY_L,
    KEY_M,
    KEY_N,
    KEY_O,
    KEY_P,
    KEY_Q,
    KEY_R,
    KEY_S,
    KEY_T,
    KEY_U,
    KEY_V,
    KEY_W,
    KEY_X,
    KEY_Y,
    KEY_Z,
    KEY_F1,
    KEY_F2,
    KEY_F3,
    KEY_F4,
    KEY_F5,
    KEY_F6,
    KEY_F7,
    KEY_F8,
    KEY_F9,
    KEY_F10,
    KEY_F11,
    KEY_F12,
    KEY_F13,
    KEY_F14,
    KEY_F15,
    KEY_F16,
    KEY_F17,
    KEY_F18,
    KEY_F19,
    KEY_F20,
    KEY_F21,
    KEY_F22,
    KEY_F23,
    KEY_F24,
    KEY_NUMLOCK,
    KEY_NUMPAD0,
    KEY_NUMPAD1,
    KEY_NUMPAD2,
    KEY_NUMPAD3,
    KEY_NUMPAD4,
    KEY_NUMPAD5,
    KEY_NUMPAD6,
    KEY_NUMPAD7,
    KEY_NUMPAD8,
    KEY_NUMPAD9,
    KEY_NUMPADCOMMA,
    KEY_NUMPADENTER,
    KEY_NUMPADEQUALS,
    KEY_DOWN,
    KEY_LEFT,
    KEY_RIGHT,
    KEY_UP,
    KEY_ADD,
    KEY_APOSTROPHE,
    KEY_BACKSLASH,
    KEY_COMMA,
    KEY_EQUALS,
    KEY_GRAVE,
    KEY_LBRACKET,
    KEY_MINUS,
    KEY_MULTIPLY,
    KEY_PERIOD,
    KEY_RBRACKET,
    KEY_SEMICOLON,
    KEY_SLASH,
    KEY_SPACE,
    KEY_TAB,
    KEY_LALT,
    KEY_LCONTROL,
    KEY_LSHIFT,
    KEY_LSUPER,
    KEY_RALT,
    KEY_RCONTROL,
    KEY_RSHIFT,
    KEY_RSUPER,
    KEY_RETURN,
    KEY_ESCAPE,
    KEY_BACKSPACE,
    KEY_DELETE,
    KEY_END,
    KEY_HOME,
    KEY_INSERT,
    KEY_PAGEDOWN,
    KEY_PAGEUP,
    KEY_CAPSLOCK,
    KEY_PAUSE,
    KEY_SCROLLLOCK,
    KEY_PRINTSCREEN,
    PRESS,
    RELEASE,
    REPEAT,
    MOUSE_BUTTON_LEFT,
    MOUSE_BUTTON_RIGHT,
    MOUSE_BUTTON_MIDDLE,
    MOUSE_BUTTON_4,
    MOUSE_BUTTON_5,
    MOUSE_BUTTON_6,
    MOUSE_BUTTON_7,
    MOUSE_BUTTON_8,
    MOD_SHIFT,
    MOD_CONTROL,
    MOD_ALT,
    MOD_SUPER,
    MOD_CAPS_LOCK,
    MOD_NUM_LOCK,
    ;

    val asPlatform: Int by lazy {
        UnityTranslateApi.instance.client.translate(this)
    }

    infix fun eq(other: Int): Boolean {
        return other == this.asPlatform
    }

    companion object {
        @JvmStatic
        fun Int.fromPlatform(): InputValue? = UnityTranslateApi.instance.client.translate(this)

        infix fun Int.eq(other: InputValue): Boolean {
            return this == other.asPlatform
        }
    }
}
